In [1]:
# from jaxtyping import install_import_hook
# with install_import_hook("chalk", "typeguard.typechecked"):
#     import chalk
from chalk import *
import numpy as np

In [2]:
d = circle(2).fill_color("black").named(Name("a")) | circle(2).fill_color("blue")


def f(subs, d):
    return d + circle(1).fill_color("red").translate_by(subs[0].get_location())


d.with_names([Name("a")], f)

In [3]:
v = circle(np.arange(1, 5)).get_envelope()

In [4]:
d = circle(np.arange(1, 5)).fill_color("black").named(Name("a")).hcat()

In [5]:
def f(subs, d):
    print(subs[0].get_location())
    return d + circle(1).fill_color("red").translate_by(subs[0].get_location()).concat()

In [6]:
d = d.with_names([Name("a")], f)
d.render_svg("tmp.svg")

[[[ 0.]
  [ 0.]
  [ 1.]]

 [[ 3.]
  [ 0.]
  [ 1.]]

 [[ 8.]
  [ 0.]
  [ 1.]]

 [[15.]
  [ 0.]
  [ 1.]]]
